steps:
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "${_ENV}", ".env"]
    dir : "cloud_computing/backend_api"

  - name: "gcr.io/cloud-builders/docker"
    dir : "cloud_computing/backend_api"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/be-sosial-media", "."]

  - name: "gcr.io/cloud-builders/docker"
    dir : "cloud_computing/backend_api"
    args: ["push", "gcr.io/$PROJECT_ID/be-sosial-media"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "be-sosial-media",
        "--image",
        "gcr.io/$PROJECT_ID/be-sosial-media",
        "--timeout",
        "1000s",
        "--port",
        "5000",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]

options:
  logging: CLOUD_LOGGING_ONLY